#!/usr/bin/env python3
"""generate_manifest.py — produce a fresh ladhe/challenges/manifest.json.

This script is committed to the public repo so anyone can verify the
challenges were generated by the same KeyGen the paper specifies,
with no fixed seeds, hidden choices, or backdoors. The script imports
directly from ladhe.py (same code path as the published paper's
algorithms). The randomness source is the OS CSPRNG (random.SystemRandom).

Runs the Ladhe key generator at each tier's bit size, captures the
public (P, h) pair, and writes:

  - manifest.json              (committed; public)
  - .witnesses/witnesses.json  (gitignored; the only secret artifact)

The witness vault is *not* needed to verify a submission — the
verifier checks structural validity + the hash. The vault exists so
the maintainer can prove (post-acceptance) that a valid witness was
in fact held at the time the challenge was generated.

Run:
  python3 generate_manifest.py
  python3 generate_manifest.py --tiers 32 64 96    # subset
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ladhe import generate_ldp_challenge, keygen  # noqa: E402

# Per-tier challenge spec. (id_prefix, bits, tier_name, reward, purpose)
DEFAULT_TIERS = [
    ("sanity-32",       32,  "SANITY_CHECK",
     "Acknowledgment in changelog",
     "Algorithm sanity test; trivially breakable by brute force."),
    ("educational-64",  64,  "EDUCATIONAL",
     "Acknowledgment in changelog",
     "Tractable for advanced attackers; below security target."),
    ("educational-96",  96,  "EDUCATIONAL",
     "Acknowledgment in changelog",
     "Educational ceiling; practical CTF challenge."),
    ("pre-crypto-128", 128,  "PRE_CRYPTOGRAPHIC",
     "Acknowledgment in changelog",
     "Hard but solvable; below 256-bit security target."),
    ("bronze-256",     256,  "BRONZE",
     "Named in public 'challenges solved' log; v2 paper acknowledgment",
     "Cryptographic security target. A break here is a real "
     "cryptanalytic result."),
]


def generate_one(id_str: str, bits: int) -> dict:
    """Run keygen at the requested bit size, return public + secret."""
    print(f"  generating {id_str} (bits={bits})...", end="", flush=True)
    t0 = time.time()
    # Use the underlying keygen so we capture the secret primes
    # alongside the public h.
    digit_count = max(2, int(bits * 0.302) + 1)
    pk, sk = keygen(up1=digit_count)
    elapsed = time.time() - t0
    print(f" done ({elapsed:.1f}s, P has {pk.prime.bit_length()} bits, "
          f"k={len(sk.primes)})")

    return {
        "id": id_str,
        "bits": bits,
        "P": pk.prime,
        "h_hex": pk.h.hex(),
        "actual_bit_length": pk.prime.bit_length(),
        "k": len(sk.primes),
        "_witness_primes": list(sk.primes),  # stripped before public output
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--tiers", type=int, nargs="*",
        help=("which bit sizes to generate (default: all tiers from "
              "32 to 256). Higher bits cost more KeyGen time."),
    )
    args = parser.parse_args()

    if args.tiers:
        tiers = [t for t in DEFAULT_TIERS if t[1] in args.tiers]
        if not tiers:
            print(f"No matching tiers for {args.tiers}; "
                  f"available: {[t[1] for t in DEFAULT_TIERS]}")
            sys.exit(1)
    else:
        tiers = DEFAULT_TIERS

    print(f"Generating {len(tiers)} challenges...")
    print()

    challenges_public = []
    witnesses = {}
    started_at = datetime.now(timezone.utc).isoformat()

    for id_prefix, bits, tier_name, reward, purpose in tiers:
        result = generate_one(id_prefix, bits)
        # Pull out the secret witness; keep public-only fields in manifest.
        witness = result.pop("_witness_primes")
        witnesses[result["id"]] = witness
        # Augment with metadata
        result["tier"] = tier_name
        result["reward"] = reward
        result["purpose"] = purpose
        challenges_public.append(result)

    finished_at = datetime.now(timezone.utc).isoformat()

    here = Path(__file__).resolve().parent

    manifest = {
        "ladhe_bounty_format_version": 1,
        "scheme": "Ladhe v1.0",
        "scheme_paper": "https://zenodo.org/records/19888480",
        "verifier": "verify_solution.py",
        "brute_force_baseline": "brute_force_baseline.py",
        "cryptanalysis_doc": "../CRYPTANALYSIS.md",
        "generator_started_at": started_at,
        "generator_finished_at": finished_at,
        "challenges": challenges_public,
    }

    out_path = here / "manifest.json"
    with open(out_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print()
    print(f"Wrote: {out_path}")

    witness_path = here / ".witnesses" / "witnesses.json"
    witness_path.parent.mkdir(parents=True, exist_ok=True)
    witness_record = {
        "generated_at": started_at,
        "warning": ("This file MUST NOT be committed to the public "
                    "repo. .gitignore protects it."),
        "witnesses": witnesses,
    }
    with open(witness_path, "w") as f:
        json.dump(witness_record, f, indent=2)
    print(f"Wrote: {witness_path}  (gitignored)")
    print()
    print("Quick verification — run the verifier on the bronze-256 "
          "challenge with its own witness to confirm everything aligns:")
    print()
    primes = witnesses["bronze-256"]
    print(f"  python3 verify_solution.py manifest.json bronze-256 "
          f"{' '.join(str(p) for p in primes)}")


if __name__ == "__main__":
    main()
